---
config_dir: "{{ ansible_user_dir }}/.config"
dotfiles_dir: "{{ ansible_user_dir }}/.dotfiles"

dotfiles_repo: "https://github.com/Mikel-Landa/dotfiles.git"

ansible_user: "mikel"

go:
  packages:
    - package: github.com/air-verse/air@latest
      cmd: air

    - package: github.com/melkeydev/go-blueprint@latest
      cmd: go-blueprint

    - package: github.com/pressly/goose/v3/cmd/goose@latest
      cmd: goose

    - package: github.com/rakyll/hey@latest
      cmd: hey

    - package: github.com/joshmedeski/sesh@latest
      cmd: sesh

    - package: github.com/spf13/cobra-cli@latest
      cmd: cobra-cli

rust:
  packages:
  - package: bat
    binary: bat
  - package: zoxide
    binary: zoxide
  - package: nu
    binary: nu
  - package: sheldon
    binary: sheldon
  - package: tree-sitter-cli
    binary: tree-sitter
  - package: fd-find
    binary: fd
  - package: tlrc
    binary: tldr

mise:
  tools:
    - chezmoi
    - kubectl
    - go
