---
common_packages:
  - git
  - curl
  - wget
  - neovim
  - python3
  - python3-pip
  - btop
  - sshfs
  - zsh
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - eza
  - ripgrep
  - zip
  - gpg
  - pkg-config
  - libssl-dev
  - build-essential
  - sshuttle
  - tmux